import type { LucideIcon, LucideProps } from "lucide-react";

export type IconComponent = LucideIcon;

type AppIconProps = LucideProps & {
  icon: IconComponent;
};

export function AppIcon({ icon: Icon, ...props }: AppIconProps) {
  return <Icon {...props} />;
}

export {
  Plus as Add01Icon,
  BookOpen as AiBookIcon,
  Bot as AiContentGenerator02Icon,
  ScanSearch as AiScanIcon,
  TriangleAlert as Alert02Icon,
  CircleAlert as AlertCircleIcon,
  Apple as AppleIcon,
  ArrowDown as ArrowDown01Icon,
  ArrowDown as ArrowDownIcon,
  ArrowLeft as ArrowLeft01Icon,
  ArrowLeft as ArrowLeftIcon,
  RefreshCw as ArrowReloadHorizontalIcon,
  ArrowRight as ArrowRight01Icon,
  ArrowRight as ArrowRightIcon,
  Undo2 as ArrowTurnBackwardIcon,
  ArrowUp as ArrowUp01Icon,
  ArrowUp as ArrowUpIcon,
  ArrowUpRight as ArrowUpRight01Icon,
  Maximize2 as AbsoluteIcon,
  Brain as BrainIcon,
  PanelTop as BrowserIcon,
  X as Cancel01Icon,
  Bot as ChatGptIcon,
  ListChecks as CheckListIcon,
  CircleCheck as CheckmarkCircle01Icon,
  CircleCheck as CheckmarkCircle02Icon,
  SquareCheck as CheckmarkSquare02Icon,
  ChevronDown,
  Sparkles as ClaudeIcon,
  Clock as Clock01Icon,
  Code as CodeIcon,
  CircleDollarSign as CoinsDollarIcon,
  Monitor as ComputerIcon,
  SquareTerminal as ComputerTerminal02Icon,
  Copy as Copy01Icon,
  Copy as CopyIcon,
  Cpu as CpuIcon,
  BrainCircuit as DeepseekIcon,
  Trash2 as Delete02Icon,
  Download as Download01Icon,
  SquarePen as Edit02Icon,
  Eye as EyeIcon,
  Star as FavouriteIcon,
  File as File01Icon,
  FileText as File02Icon,
  FilePlus as FileAddIcon,
  FilePenLine as FileEditIcon,
  FilePlus as FilePlusIcon,
  ListFilter as FilterIcon,
  Zap as FlashIcon,
  Folder as Folder01Icon,
  FolderPlus as FolderAddIcon,
  Cloud as FolderCloudIcon,
  FolderGit2 as FolderGitTwoIcon,
  FolderOpen as FolderOpenIcon,
  FolderSync as FolderTransferIcon,
  FolderTree as FolderTreeIcon,
  Gem as GoogleGeminiIcon,
  Atom as Grok02Icon,
  GitBranch as GitBranchIcon,
  GitCompare as GitCompareIcon,
  GitBranch as GithubIcon,
  Search as GlobalSearchIcon,
  Globe as Globe02Icon,
  Globe as GlobeIcon,
  Hash as HashtagIcon,
  House as Home03Icon,
  Info as InformationCircleIcon,
  KeyRound as Key01Icon,
  Keyboard as KeyboardIcon,
  ExternalLink as LinkSquare02Icon,
  LoaderCircle as Loading03Icon,
  MessageSquare as Message01Icon,
  Mic as Mic01Icon,
  Minus as MinusSignIcon,
  Wind as MistralIcon,
  Moon as Moon02Icon,
  Ellipsis as MoreHorizontalCircle01Icon,
  Ellipsis as MoreHorizontalIcon,
  CircleX as MultiplicationSignCircleIcon,
  Bell as Notification01Icon,
  BellRing as Notification03Icon,
  Palette as PaintBoardIcon,
  Paintbrush as PaintBrush04Icon,
  Pencil as PencilEdit02Icon,
  Plug as PlugIcon,
  Plus as PlusSignIcon,
  RefreshCw as Refresh01Icon,
  SquareMinus as RemoveSquareIcon,
  Bot as RobotIcon,
  Bot as RoboticIcon,
  Search as Search01Icon,
  Search as SearchIcon,
  Server as ServerStack01Icon,
  Server as ServerStack02Icon,
  Server as ServerStack03Icon,
  Settings as Settings01Icon,
  ShieldUser as ShieldUserIcon,
  PanelLeft as SidebarLeftIcon,
  Sparkles as SparklesIcon,
  Square as SquareIcon,
  Star as StarIcon,
  CircleStop as StopCircleIcon,
  Sun as Sun03Icon,
  Terminal as TerminalIcon,
  Check as Tick01Icon,
  Check as Tick02Icon,
  Wrench as ToolsIcon,
  ChevronsUpDown as UnfoldMoreIcon,
  Upload as Upload01Icon,
  Users as UserMultiple02Icon,
  Eye as ViewIcon,
  EyeOff as ViewOffSlashIcon,
  ZoomIn as ZoomInAreaIcon,
  ZoomOut as ZoomOutAreaIcon,
} from "lucide-react";
